# Generated by Django 4.2.30 on 2026-06-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Peso (kg)'),
        ),
    ]
