# Generated by Django 4.2.30 on 2026-07-01 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='contenido',
            field=models.CharField(blank=True, help_text='Ej: Caja con 12 pzas, Bolsa 100 hojas, Paquete x 6', max_length=200, verbose_name='Contenido / presentación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='piezas_por_caja',
            field=models.PositiveIntegerField(blank=True, help_text='Cuántas piezas trae la presentación de mayoreo', null=True, verbose_name='Piezas por caja/paquete'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=100, verbose_name='SKU / Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='mostrar_en_portada',
            field=models.BooleanField(default=False, verbose_name='Mostrar en portada'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio menudeo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_mayoreo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio mayoreo'),
        ),
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.producto')),
            ],
            options={
                'verbose_name': 'Foto de producto',
                'verbose_name_plural': 'Fotos de producto',
                'ordering': ['orden'],
            },
        ),
    ]
