# Generated by Django 4.2.30 on 2026-07-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_contenido_producto_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='visibilidad',
            field=models.CharField(choices=[('publico', 'Público (todos)'), ('clientes', 'Solo clientes verificados'), ('socios', 'Solo socios')], default='publico', max_length=20, verbose_name='Visible para'),
        ),
    ]
