# Generated by Django 4.2.30 on 2026-06-17 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCalculadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basico', 'Básico (sin sesión)'), ('cliente', 'Cliente registrado'), ('socio', 'Socio Comercial'), ('premium', 'Premium / Staff')], max_length=20, unique=True)),
                ('max_mb', models.PositiveIntegerField(default=10, help_text='Límite en MB')),
                ('max_paginas', models.PositiveIntegerField(default=50, help_text='Máx. páginas por cálculo')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Plan de Calculadora',
                'verbose_name_plural': 'Planes de Calculadora',
            },
        ),
        migrations.CreateModel(
            name='HistorialCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('num_paginas', models.PositiveIntegerField(default=0)),
                ('tipo_hoja', models.CharField(default='bond', max_length=30)),
                ('precio_minimo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_maximo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tiempo_proceso', models.FloatField(default=0, help_text='Segundos')),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cálculo',
                'verbose_name_plural': 'Historial de Cálculos',
                'ordering': ['-creado'],
            },
        ),
    ]
