# Generated by Django 4.2.30 on 2026-07-01 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('atendida', 'Con agente'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('modo_ia', models.BooleanField(default=False, verbose_name='Atendida por IA')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cerrada', models.DateTimeField(blank=True, null=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats_atendidos', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('cliente', 'Cliente'), ('agente', 'Agente'), ('ia', 'IA'), ('sistema', 'Sistema')], max_length=10)),
                ('texto', models.TextField()),
                ('enviado', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.conversacion')),
            ],
            options={
                'ordering': ['enviado'],
            },
        ),
    ]
