# Generated by Django 4.2.30 on 2026-07-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversacion',
            name='modo_ia',
        ),
        migrations.AddField(
            model_name='conversacion',
            name='telegram_msg_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
