# Generated by Django 4.2.30 on 2026-07-01 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_telegram_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='visitante_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='visitante_nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='visitante_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='origen',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('agente', 'Agente'), ('sistema', 'Sistema')], max_length=10),
        ),
    ]
