# Generated by Django 4.2.30 on 2026-06-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_negocio',
            field=models.ImageField(blank=True, null=True, upload_to='verificacion/', verbose_name='Foto del negocio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificado',
            field=models.BooleanField(default=False, verbose_name='Cliente verificado'),
        ),
    ]
