# Generated by Django 4.2.30 on 2026-06-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_foto_negocio_usuario_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dir_calle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Calle y número'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dir_ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad / Municipio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dir_colonia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dir_cp',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dir_estado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado'),
        ),
    ]
