# Generated by Django 4.2.30 on 2026-07-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_dir_calle_usuario_dir_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='precio_envio_especial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se define, este precio reemplaza la tarifa estándar PapeExpress para este cliente.', max_digits=8, null=True, verbose_name='Tarifa de envío especial ($)'),
        ),
    ]
