# Generated by Django 4.2.30 on 2026-06-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociocomercial',
            options={'ordering': ['-destacado', 'nombre'], 'verbose_name': 'Socio Comercial', 'verbose_name_plural': 'Socios Comerciales'},
        ),
        migrations.AddField(
            model_name='sociocomercial',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Texto atractivo para clientes'),
        ),
        migrations.AddField(
            model_name='sociocomercial',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Aparece primero y con destacado visual'),
        ),
        migrations.AddField(
            model_name='sociocomercial',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL completa del perfil/página de Facebook'),
        ),
        migrations.AddField(
            model_name='sociocomercial',
            name='foto_negocio',
            field=models.ImageField(blank=True, null=True, upload_to='socios/fotos/'),
        ),
        migrations.AddField(
            model_name='sociocomercial',
            name='horario',
            field=models.CharField(blank=True, help_text='Ej: Lun-Vie 9am-7pm, Sáb 9am-3pm', max_length=200),
        ),
        migrations.AddField(
            model_name='sociocomercial',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sociocomercial',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='socios/logos/'),
        ),
        migrations.AddField(
            model_name='sociocomercial',
            name='slogan',
            field=models.CharField(blank=True, help_text='Frase corta del negocio', max_length=200),
        ),
        migrations.AddField(
            model_name='sociocomercial',
            name='whatsapp_1',
            field=models.CharField(blank=True, help_text='Número con código país, ej: 5215512345678', max_length=20),
        ),
        migrations.AddField(
            model_name='sociocomercial',
            name='whatsapp_2',
            field=models.CharField(blank=True, help_text='Segundo número WhatsApp (opcional)', max_length=20),
        ),
    ]
