# Generated by Django 4.2.30 on 2026-06-17 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(blank=True, default='📦', max_length=10)),
                ('color', models.CharField(blank=True, default='#6c757d', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoría POS',
                'verbose_name_plural': 'Categorías POS',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClientePOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente POS',
                'verbose_name_plural': 'Clientes POS',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CompraProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, help_text='Folio/número del ticket del proveedor', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibida', 'Recibida'), ('parcial', 'Parcial'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now)),
                ('ticket_imagen', models.ImageField(blank=True, help_text='Foto del ticket/factura del proveedor', null=True, upload_to='pos/tickets/')),
                ('ticket_pdf', models.FileField(blank=True, null=True, upload_to='pos/tickets/')),
                ('analisis_ocr', models.TextField(blank=True, help_text='Texto extraído del ticket por OCR/IA')),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compra a Proveedor',
                'verbose_name_plural': 'Compras a Proveedores',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Alerta Telegram cuando llegue a este nivel', max_digits=12)),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio ponderado', max_digits=10)),
                ('ultimo_movimiento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventario',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(blank=True, max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('mayoreo', 'Mayoreo'), ('menudeo', 'Menudeo'), ('mixto', 'Mayoreo y Menudeo')], default='mixto', max_length=10)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='pos.clientepos')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['cliente', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('credito', 'A crédito')], default='abierta', max_length=15)),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('credito', 'Crédito / Anticipo'), ('mixto', 'Pago mixto')], default='efectivo', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, help_text='Costo real para calcular ganancia', max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='pos.sucursal')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ProductoPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de barras o clave interna', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pos/productos/')),
                ('unidad', models.CharField(default='pieza', help_text='pieza, caja, kg, litro, etc.', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='pos.categoriapos')),
            ],
            options={
                'verbose_name': 'Producto POS',
                'verbose_name_plural': 'Productos POS',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioHistoricoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.compraproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_proveedores', to='pos.productopos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_historicos', to='pos.proveedor')),
            ],
            options={
                'verbose_name': 'Precio Histórico Proveedor',
                'verbose_name_plural': 'Precios Históricos Proveedores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada de mercancía'), ('salida', 'Salida por venta'), ('ajuste', 'Ajuste manual'), ('devolucion', 'Devolución'), ('traslado', 'Traslado entre sucursales')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_antes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_despues', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referencia', models.CharField(blank=True, help_text='Nº venta, compra, etc.', max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='pos.compraproveedor')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='pos.inventario')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='pos.productopos'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='pos.sucursal'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nivel_precio', models.PositiveSmallIntegerField(default=1, help_text='1=menudeo, 2=mayoreo, 3=especial')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.productopos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pos.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pos.compraproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.productopos')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
            },
        ),
        migrations.AddField(
            model_name='compraproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='pos.proveedor'),
        ),
        migrations.AddField(
            model_name='compraproveedor',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='pos.sucursal'),
        ),
        migrations.AddField(
            model_name='compraproveedor',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_tel', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción del pedido')),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('anticipo_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entregado', models.BooleanField(default=False)),
                ('fecha_prometida', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticipos', to='pos.sucursal')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anticipo', to='pos.venta')),
            ],
            options={
                'verbose_name': 'Anticipo / Pedido',
                'verbose_name_plural': 'Anticipos / Pedidos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='pos.venta')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('cajero', 'Cajero'), ('gerente', 'Gerente de sucursal'), ('almacen', 'Encargado de almacén')], default='cajero', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='pos.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_pos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de Sucursal',
                'verbose_name_plural': 'Usuarios de Sucursal',
                'unique_together': {('usuario', 'sucursal')},
            },
        ),
        migrations.CreateModel(
            name='PrecioPorSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_1', models.DecimalField(decimal_places=2, help_text='Precio menudeo', max_digits=10)),
                ('precio_2', models.DecimalField(blank=True, decimal_places=2, help_text='Precio mayoreo / 2do nivel', max_digits=10, null=True)),
                ('precio_3', models.DecimalField(blank=True, decimal_places=2, help_text='Precio especial / 3er nivel', max_digits=10, null=True)),
                ('en_oferta', models.BooleanField(default=False)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='pos.productopos')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='pos.sucursal')),
            ],
            options={
                'verbose_name': 'Precio por Sucursal',
                'verbose_name_plural': 'Precios por Sucursal',
                'unique_together': {('producto', 'sucursal')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('producto', 'sucursal')},
        ),
    ]
