# Generated by Django 4.2.30 on 2026-06-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopos',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Peso por unidad en kg. Usado para calcular envíos.', max_digits=6, verbose_name='Peso (kg)'),
        ),
    ]
