# Generated by Django 4.2.30 on 2026-06-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_productopos_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosucursal',
            name='rol',
            field=models.CharField(choices=[('cajero', 'Cajero'), ('vendedor', 'Vendedor'), ('gerente', 'Gerente de sucursal'), ('almacen', 'Encargado de almacén')], default='cajero', max_length=20),
        ),
    ]
