# Generated by Django 4.2.30 on 2026-07-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_usuariosucursal_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopos',
            name='favorito_pos',
            field=models.BooleanField(default=False, help_text='Aparece en la pestaña "Favoritos" al abrir el POS.', verbose_name='Favorito del POS'),
        ),
    ]
