# Generated by Django 4.2.30 on 2026-07-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_favorito_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pos/sucursales/', verbose_name='Logo de la sucursal'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número sin espacios ni +52, ej: 5512345678', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
