# Generated by Django 4.2.30 on 2026-07-01 16:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_logo_whatsapp_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_reinversion', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Porcentaje de la ganancia neta sugerido para reinvertir en mercancía.', max_digits=5, verbose_name='% Reinversión sugerida')),
                ('whatsapp_general', models.CharField(blank=True, help_text='Número sin +52 ni espacios. Se usa en tickets si la sucursal no tiene uno propio.', max_length=20, verbose_name='WhatsApp general')),
            ],
            options={
                'verbose_name': 'Configuración POS',
                'verbose_name_plural': 'Configuración POS',
            },
        ),
    ]
