# Generated by Django 4.2.30 on 2026-07-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_config_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('renta', 'Renta / local'), ('sueldos', 'Sueldos y salarios'), ('internet', 'Internet'), ('electricidad', 'Electricidad / luz'), ('agua', 'Agua'), ('telefono', 'Teléfono / celular'), ('mantenimiento', 'Mantenimiento'), ('publicidad', 'Publicidad / marketing'), ('contabilidad', 'Contabilidad / honorarios'), ('otros', 'Otros')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto mensual ($)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_fijos', to='pos.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Gasto Fijo',
                'verbose_name_plural': 'Gastos Fijos',
                'ordering': ['sucursal', 'tipo'],
            },
        ),
    ]
