# Generated by Django 4.2.30 on 2026-07-01 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0007_gastos_fijos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCancelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cancelacion', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cancelacion', to='pos.venta')),
            ],
            options={
                'verbose_name': 'Solicitud de Cancelación',
                'verbose_name_plural': 'Solicitudes de Cancelación',
            },
        ),
    ]
