# Generated by Django 4.2.30 on 2026-07-01 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0008_solicitud_cancelacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraspasoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado / En camino'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='solicitado', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('recibido_en', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_solicitados', to=settings.AUTH_USER_MODEL)),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_entrada', to='pos.sucursal')),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_salida', to='pos.sucursal')),
            ],
            options={
                'verbose_name': 'Traspaso entre Sucursales',
                'verbose_name_plural': 'Traspasos entre Sucursales',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTraspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, help_text='Puede diferir si llegó incompleto', max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.productopos')),
                ('traspaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pos.traspasosucursal')),
            ],
            options={
                'verbose_name': 'Detalle de Traspaso',
            },
        ),
    ]
