# Generated by Django 4.2.30 on 2026-07-01 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_traspasos_sucursales'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalletraspaso',
            name='precio_traspaso_unit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de traspaso (P4) al momento de crear', max_digits=10),
        ),
        migrations.AddField(
            model_name='detalletraspaso',
            name='subtotal_traspaso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='precioporsucursal',
            name='precio_traspaso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio interno para traspasos entre sucursales (P4)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='traspasosucursal',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('credito', 'A crédito')], max_length=20),
        ),
        migrations.AddField(
            model_name='traspasosucursal',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traspasosucursal',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total a pagar por el destino al origen', max_digits=12),
        ),
        migrations.AddField(
            model_name='traspasosucursal',
            name='venta_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspaso', to='pos.venta'),
        ),
    ]
