# Generated by Django 4.2.30 on 2026-07-02 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0011_gasto_operativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('cambio_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cambio inicial ($)')),
                ('apertura_en', models.DateTimeField(auto_now_add=True)),
                ('efectivo_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Efectivo contado al cierre ($)')),
                ('cierre_en', models.DateTimeField(blank=True, null=True)),
                ('notas_cierre', models.TextField(blank=True)),
                ('total_ventas_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_retiros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gastos_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('efectivo_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, help_text='Positivo = sobra, Negativo = falta', max_digits=12)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to='pos.sucursal')),
                ('usuario_apertura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperturas_caja', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha'],
                'unique_together': {('sucursal', 'fecha')},
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='cambio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cambio devuelto al cliente', max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Efectivo entregado por el cliente', max_digits=12),
        ),
        migrations.CreateModel(
            name='RetiroEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='pos.cierrecaja')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retiro de Efectivo',
                'verbose_name_plural': 'Retiros de Efectivo',
                'ordering': ['-fecha'],
            },
        ),
    ]
