# Generated by Django 4.2.30 on 2026-07-02 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0012_caja_diaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recarga', 'Recarga de celular'), ('servicio', 'Pago de servicio')], max_length=10)),
                ('servicio', models.CharField(blank=True, choices=[('cfe', 'CFE / Luz'), ('telmex', 'Telmex / Internet'), ('agua', 'Agua'), ('gas', 'Gas'), ('telcel', 'Telcel'), ('att', 'AT&T'), ('movistar', 'Movistar'), ('bait', 'Bait'), ('otro', 'Otro')], help_text='Solo para pagos de servicio', max_length=20)),
                ('telefono', models.CharField(blank=True, help_text='Número recargado (solo recargas)', max_length=15)),
                ('referencia', models.CharField(blank=True, help_text='Número de cuenta, contrato, etc.', max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto cobrado al cliente ($)')),
                ('comision', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Comisión ($)')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_servicio', to='pos.sucursal')),
            ],
            options={
                'verbose_name': 'Transacción de Servicio',
                'verbose_name_plural': 'Transacciones de Servicio',
                'ordering': ['-fecha'],
            },
        ),
    ]
