# Generated by Django 4.2.30 on 2026-07-02 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0013_transacciones_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='notas_revision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='revisado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_revisados', to=settings.AUTH_USER_MODEL),
        ),
    ]
