# Generated by Django 4.2.30 on 2026-07-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_revision_cierre_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='total_comisiones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='total_monto_servicios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
