# Generated by Django 4.2.30 on 2026-06-17 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiguraFomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_referencia', models.ImageField(blank=True, null=True, upload_to='figuras/imagenes/')),
                ('etapa_actual', models.CharField(choices=[('propuesta', 'Propuesta'), ('diseño', 'Diseño'), ('armado_digital', 'Armado Digital'), ('muestra', 'Muestra'), ('materiales', 'Materiales y Costos'), ('corte', 'Corte'), ('armado', 'Armado'), ('embolsado', 'Embolsado'), ('etiquetado', 'Etiquetado'), ('terminado', 'Terminado')], default='propuesta', max_length=30)),
                ('cantidad_planificada', models.PositiveIntegerField(default=0)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0, help_text='Piezas listas para venta / pedidos de socios')),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiene_fomy', models.BooleanField(default=False, verbose_name='¿Hay fomy disponible?')),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('archivo_studio3', models.FileField(blank=True, help_text='Archivo .studio3 para la máquina de corte', null=True, upload_to='figuras/studio3/', verbose_name='Plantilla Studio3')),
                ('archivo_instrucciones_pdf', models.FileField(blank=True, help_text='PDF con instrucciones de armado', null=True, upload_to='figuras/instrucciones/', verbose_name='Instrucciones PDF')),
                ('archivo_instrucciones_word', models.FileField(blank=True, help_text='Word editable con instrucciones de armado', null=True, upload_to='figuras/instrucciones/', verbose_name='Instrucciones Word (.docx)')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figuras_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Figura de Fomy',
                'verbose_name_plural': 'Figuras de Fomy',
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='Libreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='libretas/')),
                ('num_hojas', models.PositiveIntegerField(default=100)),
                ('tipo_pasta', models.CharField(blank=True, max_length=100)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('mostrar_en_portada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Libreta',
                'verbose_name_plural': 'Libretas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_anterior', models.CharField(choices=[('propuesta', 'Propuesta'), ('diseño', 'Diseño'), ('armado_digital', 'Armado Digital'), ('muestra', 'Muestra'), ('materiales', 'Materiales y Costos'), ('corte', 'Corte'), ('armado', 'Armado'), ('embolsado', 'Embolsado'), ('etiquetado', 'Etiquetado'), ('terminado', 'Terminado')], max_length=30)),
                ('etapa_nueva', models.CharField(choices=[('propuesta', 'Propuesta'), ('diseño', 'Diseño'), ('armado_digital', 'Armado Digital'), ('muestra', 'Muestra'), ('materiales', 'Materiales y Costos'), ('corte', 'Corte'), ('armado', 'Armado'), ('embolsado', 'Embolsado'), ('etiquetado', 'Etiquetado'), ('terminado', 'Terminado')], max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('figura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='produccion.figurafomy')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Etapa',
                'verbose_name_plural': 'Historial de Etapas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FotoFigura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='figuras/fotos/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('subida', models.DateTimeField(auto_now_add=True)),
                ('figura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='produccion.figurafomy')),
            ],
            options={
                'verbose_name': 'Foto de Figura',
                'verbose_name_plural': 'Fotos de Figura',
                'ordering': ['orden', 'subida'],
            },
        ),
    ]
