# Generated by Django 4.2.30 on 2026-06-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, default=180, max_digits=8, verbose_name='Precio base ($)')),
                ('peso_base_kg', models.DecimalField(decimal_places=2, default=5, max_digits=6, verbose_name='Peso base incluido (kg)')),
                ('precio_kg_extra', models.DecimalField(decimal_places=2, default=30, max_digits=8, verbose_name='Precio por kg extra ($)')),
                ('activa', models.BooleanField(default=True, verbose_name='Tarifa activa')),
            ],
            options={
                'verbose_name': 'Tarifa de Envío PapeExpress',
                'verbose_name_plural': 'Tarifas de Envío PapeExpress',
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='direccion_calle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Calle y número'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='direccion_ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad / Municipio'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='direccion_colonia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='direccion_cp',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='direccion_estado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_requerida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha requerida'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='metodo_envio',
            field=models.CharField(choices=[('papeexpress', 'Envío PapeExpress (CDMX / EdoMex)'), ('paqueteria', 'Paquetería (FedEx, DHL, etc.)'), ('recoger', 'Recoger en tienda')], default='papeexpress', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='notas_entrega',
            field=models.TextField(blank=True, verbose_name='Notas de entrega'),
        ),
    ]
