# Generated by Django 4.2.30 on 2026-07-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_tarifaenvio_cotizacion_costo_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifaenvio',
            name='monto_minimo_etiqueta',
            field=models.CharField(blank=True, help_text='Ej: "¡Envío gratis en compras mayores a $1,500!"', max_length=80, verbose_name='Etiqueta monto mínimo'),
        ),
        migrations.AddField(
            model_name='tarifaenvio',
            name='monto_minimo_promo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si el subtotal del pedido supera este monto se aplica el precio especial', max_digits=10, null=True, verbose_name='Monto mínimo para promo ($)'),
        ),
        migrations.AddField(
            model_name='tarifaenvio',
            name='precio_monto_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pon 0 para envío gratis. Ej: $0 o $50', max_digits=8, null=True, verbose_name='Precio de envío con monto mínimo ($)'),
        ),
        migrations.AddField(
            model_name='tarifaenvio',
            name='promo_activa',
            field=models.BooleanField(default=False, verbose_name='Promo por fechas activa'),
        ),
        migrations.AddField(
            model_name='tarifaenvio',
            name='promo_etiqueta',
            field=models.CharField(blank=True, help_text='Texto que ve el cliente. Ej: "¡Envío especial de temporada!"', max_length=80, verbose_name='Etiqueta promo'),
        ),
        migrations.AddField(
            model_name='tarifaenvio',
            name='promo_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de promo'),
        ),
        migrations.AddField(
            model_name='tarifaenvio',
            name='promo_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de promo'),
        ),
        migrations.AddField(
            model_name='tarifaenvio',
            name='promo_precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio fijo de envío durante la promo. Ej: $120', max_digits=8, null=True, verbose_name='Precio con promo ($)'),
        ),
    ]
